general_tasks = [
    "100-General Absence",
    "110-Public Holiday - voor voltijdse medewerkers",
    "120-Vacation, Pers. Holiday - voor voltijdse medewerkers",
    "121-Sickness - voor voltijdse medewerkers",
    "122-Unpaid Leave - voor voltijdse medewerkers",
    "123-Other Paid Leave + RECUP - voor voltijdse medewerkers",
    "300-BD Opportunity Time",
    "700-General Attendance (Meetings, Marketing, Works Council)",
    "705-Meetings",
    "710-Travel (Geen woon-werk ; niet project gerelateerd)",
    "720-Administration",
    "730-Training Received",
    "735-Training Delivered",
    "740-Management",
    "750-People Management (Performance Review &CAREER)",
    "760-Knowledge Management",
    "770-Counseling/Mentoring (Training Delivered, Coaching)",
    "775-Bench",
    "776-Voluntary Service",
    "777-Union Activities",
    "791 Hol/Vac - PT : part time equivalent to absence code 120",
    "792 Public Holiday - PT : part time equivalent to absence code 110",
    "793 Sickness - PT : part time equivalent to absence code 121",
    "794 Unpaid Leave - PT : part time equivalent to absence code 122",
    "795 Other Paid Leave - PT : part time equivalent to absence code 123 + RECUP",
    "799 - Contractor Non Attendance",
    "Special task to move to next week-enter 00:01-Don't enter other hours-Close week",
]
